# Generated by Django 4.1.5 on 2023-01-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ablog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default=" My Freakin' Awesome blog", max_length=255),
        ),
    ]
